#!/usr/bin/env bash
set -euo pipefail

if [[ -n "${GOOGLE_CREDENTIALS_B64:-}" ]]; then
  printf '%s' "$GOOGLE_CREDENTIALS_B64" | base64 --decode > credentials.json
  printf '%s' "$GOOGLE_TOKEN_B64" | base64 --decode > token.json
  chmod 600 credentials.json token.json
fi

cat > .env <<EOF
CANVAS_BASE_URL=${CANVAS_BASE_URL}
CANVAS_API_TOKEN=${CANVAS_API_TOKEN}
CANVAS_LOOKAHEAD_DAYS=30
CANVAS_ANNOUNCEMENT_DAYS=14
APP_TIMEZONE=America/Toronto
CANVAS_MATERIALS_DIR=data/materials
CANVAS_MATERIALS_INDEX=data/materials_index.json
CANVAS_MATERIAL_MAX_MB=25
CANVAS_MATERIAL_FUTURE_DAYS=550
COURSE_SCHEDULE_FILE=data/course_schedule.json
ANNOUNCEMENT_DATES_INDEX=data/announcement_dates_index.json
LECTURE_QUIZ_STATE_FILE=data/lecture_quiz_state.json
LECTURE_QUIZ_RETRY_HOURS=30
DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
DISCORD_ANNOUNCEMENTS_CHANNEL_ID=${DISCORD_ANNOUNCEMENTS_CHANNEL_ID}
DISCORD_CALENDAR_CHANNEL_ID=${DISCORD_CALENDAR_CHANNEL_ID}
DISCORD_QUIZ_CHANNEL_ID=${DISCORD_QUIZ_CHANNEL_ID}
GOOGLE_CREDENTIALS_FILE=credentials.json
GOOGLE_TOKEN_FILE=token.json
GOOGLE_CALENDAR_NAME=${GOOGLE_CALENDAR_NAME:-Attendr}
GOOGLE_CREATE_CALENDAR_IF_MISSING=true
GOOGLE_MARK_SUBMITTED=true
GOOGLE_STUDY_CALENDAR_NAME=${GOOGLE_STUDY_CALENDAR_NAME:-Attendr Study Plan}
STUDY_WORKER_URL=${STUDY_WORKER_URL}
STUDY_SYNC_SECRET=${STUDY_SYNC_SECRET}
GEMINI_API_KEY=${GEMINI_API_KEY}
GEMINI_MODEL=gemini-3.6-flash
DAILY_QUIZ_TOPIC=${DAILY_QUIZ_TOPIC:-}
DAILY_TOPICS_FILE=data/daily_topics.json
EOF
chmod 600 .env
