"""Personal academic assistant integrations."""

from .ai_assistant import (
    AIAssistant,
    AIConfigurationError,
    AIInputError,
    AIProviderError,
    MajorDeadline,
    HybridQuizQuestion,
    PDFExtractionError,
    PDFTextChunk,
    QuizQuestion,
    SyllabusEntry,
    extract_pdf_text_chunks,
    extract_powerpoint_text_chunks,
    hybrid_quiz_discord_payload,
    quiz_discord_payload,
    send_quiz_to_discord,
    send_hybrid_quiz_to_discord,
)
from .calendar_sync import (
    CalendarAPIError,
    CalendarAuthenticationError,
    CalendarConfigurationError,
    CalendarSyncEntry,
    CalendarSyncReport,
    GoogleCalendarAuthenticator,
    GoogleCalendarSync,
)
from .canvas_client import (
    AcademicItem,
    Announcement,
    CanvasAPIError,
    CanvasAuthenticationError,
    CanvasClient,
    CanvasConfigurationError,
    CanvasSnapshot,
    CourseSummary,
    MaterialDownloadReport,
    LectureMaterial,
    LectureMaterialDownloadReport,
    SyllabusMaterial,
)
from .announcement_dates import AnnouncementDatesReport, AnnouncementDatesSync
from .course_schedule import AcademicDate, ClassSession, CourseSchedule
from .lecture_quiz import LectureQuizReport, LectureQuizRunner
from .materials_sync import (
    CourseMaterialsSync,
    MaterialsConfigurationError,
    MaterialsStateError,
    MaterialsSyncReport,
)
from .notifier import (
    DiscordConfigurationError,
    DiscordNotificationError,
    DiscordNotifier,
    DiscordRateLimitError,
    JsonNotificationState,
    NotificationReport,
    NotificationState,
)

__all__ = [
    "AIAssistant",
    "AIConfigurationError",
    "AIInputError",
    "AIProviderError",
    "AcademicItem",
    "Announcement",
    "AnnouncementDatesReport",
    "AnnouncementDatesSync",
    "CalendarAPIError",
    "CalendarAuthenticationError",
    "CalendarConfigurationError",
    "CalendarSyncEntry",
    "CalendarSyncReport",
    "CanvasAPIError",
    "CanvasAuthenticationError",
    "CanvasClient",
    "CanvasConfigurationError",
    "CanvasSnapshot",
    "CourseMaterialsSync",
    "CourseSchedule",
    "ClassSession",
    "AcademicDate",
    "CourseSummary",
    "DiscordConfigurationError",
    "DiscordNotificationError",
    "DiscordNotifier",
    "DiscordRateLimitError",
    "GoogleCalendarAuthenticator",
    "GoogleCalendarSync",
    "JsonNotificationState",
    "MajorDeadline",
    "HybridQuizQuestion",
    "LectureMaterial",
    "LectureMaterialDownloadReport",
    "LectureQuizReport",
    "LectureQuizRunner",
    "MaterialDownloadReport",
    "MaterialsConfigurationError",
    "MaterialsStateError",
    "MaterialsSyncReport",
    "NotificationReport",
    "NotificationState",
    "PDFExtractionError",
    "PDFTextChunk",
    "QuizQuestion",
    "SyllabusEntry",
    "SyllabusMaterial",
    "extract_pdf_text_chunks",
    "extract_powerpoint_text_chunks",
    "hybrid_quiz_discord_payload",
    "quiz_discord_payload",
    "send_quiz_to_discord",
    "send_hybrid_quiz_to_discord",
]
