"""Personal academic assistant integrations."""

from .ai_assistant import (
    AIAssistant,
    AIConfigurationError,
    AIInputError,
    AIProviderError,
    PDFExtractionError,
    PDFTextChunk,
    QuizQuestion,
    SyllabusEntry,
    extract_pdf_text_chunks,
    quiz_discord_payload,
    send_quiz_to_discord,
)
from .calendar_sync import (
    CalendarAPIError,
    CalendarAuthenticationError,
    CalendarConfigurationError,
    CalendarSyncEntry,
    CalendarSyncReport,
    GoogleCalendarAuthenticator,
    GoogleCalendarSync,
)
from .canvas_client import (
    AcademicItem,
    Announcement,
    CanvasAPIError,
    CanvasAuthenticationError,
    CanvasClient,
    CanvasConfigurationError,
    CanvasSnapshot,
    CourseSummary,
)
from .notifier import (
    DiscordConfigurationError,
    DiscordNotificationError,
    DiscordNotifier,
    DiscordRateLimitError,
    JsonNotificationState,
    NotificationReport,
    NotificationState,
)

__all__ = [
    "AIAssistant",
    "AIConfigurationError",
    "AIInputError",
    "AIProviderError",
    "AcademicItem",
    "Announcement",
    "CalendarAPIError",
    "CalendarAuthenticationError",
    "CalendarConfigurationError",
    "CalendarSyncEntry",
    "CalendarSyncReport",
    "CanvasAPIError",
    "CanvasAuthenticationError",
    "CanvasClient",
    "CanvasConfigurationError",
    "CanvasSnapshot",
    "CourseSummary",
    "DiscordConfigurationError",
    "DiscordNotificationError",
    "DiscordNotifier",
    "DiscordRateLimitError",
    "GoogleCalendarAuthenticator",
    "GoogleCalendarSync",
    "JsonNotificationState",
    "NotificationReport",
    "NotificationState",
    "PDFExtractionError",
    "PDFTextChunk",
    "QuizQuestion",
    "SyllabusEntry",
    "extract_pdf_text_chunks",
    "quiz_discord_payload",
    "send_quiz_to_discord",
]
