"""Public integration exports, loaded only when requested."""

from importlib import import_module

_EXPORTS = {
    "AIAssistant": "ai_assistant",
    "AIConfigurationError": "ai_assistant",
    "AIInputError": "ai_assistant",
    "AIProviderError": "ai_assistant",
    "MajorDeadline": "ai_assistant",
    "HybridQuizQuestion": "ai_assistant",
    "GroundedSummaryPoint": "ai_assistant",
    "LectureSummary": "ai_assistant",
    "PDFExtractionError": "ai_assistant",
    "PDFTextChunk": "ai_assistant",
    "QuizQuestion": "ai_assistant",
    "SyllabusEntry": "ai_assistant",
    "extract_pdf_text_chunks": "ai_assistant",
    "extract_powerpoint_text_chunks": "ai_assistant",
    "hybrid_quiz_discord_payload": "ai_assistant",
    "quiz_discord_payload": "ai_assistant",
    "send_quiz_to_discord": "ai_assistant",
    "send_hybrid_quiz_to_discord": "ai_assistant",
    "CalendarAPIError": "calendar_sync",
    "CalendarAuthenticationError": "calendar_sync",
    "CalendarConfigurationError": "calendar_sync",
    "CalendarSyncEntry": "calendar_sync",
    "CalendarSyncReport": "calendar_sync",
    "GoogleCalendarAuthenticator": "calendar_sync",
    "GoogleCalendarSync": "calendar_sync",
    "AcademicItem": "canvas_client",
    "Announcement": "canvas_client",
    "CanvasAPIError": "canvas_client",
    "CanvasAuthenticationError": "canvas_client",
    "CanvasClient": "canvas_client",
    "CanvasConfigurationError": "canvas_client",
    "CanvasSnapshot": "canvas_client",
    "CourseSummary": "canvas_client",
    "MaterialDownloadReport": "canvas_client",
    "LectureMaterial": "canvas_client",
    "LectureMaterialDownloadReport": "canvas_client",
    "SyllabusMaterial": "canvas_client",
    "AnnouncementDatesReport": "announcement_dates",
    "AnnouncementDatesSync": "announcement_dates",
    "AcademicDate": "course_schedule",
    "ClassSession": "course_schedule",
    "CourseSchedule": "course_schedule",
    "LectureQuizReport": "lecture_quiz",
    "LectureReviewReport": "lecture_quiz",
    "LectureQuizRunner": "lecture_quiz",
    "LectureContentBundle": "lecture_content",
    "LectureContentSource": "lecture_content",
    "build_lecture_content_bundle": "lecture_content",
    "lecture_summary_discord_payload": "lecture_summary",
    "CourseMaterialsSync": "materials_sync",
    "MaterialsConfigurationError": "materials_sync",
    "MaterialsStateError": "materials_sync",
    "MaterialsSyncReport": "materials_sync",
    "DiscordConfigurationError": "notifier",
    "DiscordNotificationError": "notifier",
    "DiscordQuietHoursError": "notifier",
    "DiscordNotifier": "notifier",
    "DiscordRateLimitError": "notifier",
    "JsonNotificationState": "notifier",
    "NotificationReport": "notifier",
    "NotificationState": "notifier",
    "BusyInterval": "study_planner",
    "StudyPlanReport": "study_planner",
    "StudyPlanner": "study_planner",
    "StudyRemoteState": "study_planner",
    "StudyTemplate": "study_planner",
}
__all__ = list(_EXPORTS)


def __getattr__(name: str):
    if name not in _EXPORTS:
        raise AttributeError(name)
    value = getattr(import_module(f".{_EXPORTS[name]}", __name__), name)
    globals()[name] = value
    return value
